### ISSUE TITLE
ability to add contrast to tab bar

### ISSUE THREAD

**Issue by steveoh** [nordtheme/atom-ui#73]
When using the split pane it is very difficult to tell apart the pane from the text area.

![image](https://user-images.githubusercontent.com/325813/38584840-db6f3f3e-3cd4-11e8-8671-dda4e343dfbf.png)

It would be nice to add a border to the top or have the ability to increase the contrast to tell the difference.

**Comment by arcticicestudio** [comment]
Thanks for your improvement suggestion :+1: 
There are also already [many notes on how to improve the UI in the backlog][n], but unfortunately my free time to work on my projects is rare due to study and job at least until July. I'll add a new note for this improvement. The plan is to implement something like the Material theme to use shadows and contrast differences for more depth that users can enable though the theme settings.

[n]: https://github.com/arcticicestudio/nord-atom-ui/projects/1#column-76924

**Comment by slnt** [comment]
+1 for this, would be very helpful :)

**Comment by lawrence-dass** [comment]
I'd like to work on this, please.
